<script setup>
import DataRow from './DataRow.vue'

const fakeData = [{id: 111,
  episode_name: "Fakey Pilot",
  set: "1 of 1",
  note: null,
  still_path: null,
  season_num: "1",
  show_name: "Fakey",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standard), Kind(Standing Back), Kind(True)",
  setting: "Adventure",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 112,
  episode_name: "Fakey First",
  set: "1 of 2",
  note: null,
  still_path: null,
  season_num: "1",
  show_name: "Fakey",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standard), Kind(Standing Back), Kind(True)",
  setting: "Adventure",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 113,
  episode_name: "Fakey Another",
  set: "2 of 2",
  note: null,
  still_path: null,
  season_num: "1",
  show_name: "Fakey",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standing Back), Problem Solver, Wise",
  setting: "Home",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 211,
  episode_name: "Notreal Pilot",
  set: "1 of 1",
  note: null,
  still_path: null,
  season_num: "2",
  show_name: "Notreal",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standard), Kind(Standing Back), Kind(True)",
  setting: "Adventure",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 212,
  episode_name: "Not real First",
  set: "1 of 2",
  note: null,
  still_path: null,
  season_num: "2",
  show_name: "Notreal",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standard), Kind(Standing Back), Kind(True)",
  setting: "Adventure",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 213,
  episode_name: "Not real Another",
  set: "2 of 2",
  note: null,
  still_path: null,
  season_num: "2",
  show_name: "Notreal",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standing Back), Problem Solver, Wise",
  setting: "Home",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 221,
  episode_name: "Notreal Pilot",
  set: "1 of 1",
  note: null,
  still_path: null,
  season_num: "2",
  show_name: "Notreal",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standard), Kind(Standing Back), Kind(True)",
  setting: "Adventure",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 222,
  episode_name: "Not real First",
  set: "1 of 2",
  note: null,
  still_path: null,
  season_num: "2",
  show_name: "Notreal",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standard), Kind(Standing Back), Kind(True)",
  setting: "Adventure",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"},
 {id: 223,
  episode_name: "Not real Another",
  set: "2 of 2",
  note: null,
  still_path: null,
  season_num: "2",
  show_name: "Notreal",
  img: "/needtofix",
  website: "google.com",
  purchase: null,
  flatrate: null,
  sel: "Kind(Standing Back), Problem Solver, Wise",
  setting: "Home",
  heads_up: "Death(non-sentient)",
  situations: "Getting Hurt, Sharing"}]


</script>

<template>
  <main>
    <DataRow v-for="rowObject in fakeData" :rowObject="rowObject" />
  </main>


</template>

<style scoped>

</style>